[package]
name = "edioc-studio"
version = "0.1.0"
edition = "2024"

[dependencies]
bollard = "0.20.0"
crossterm = "0.29.0"
ratatui = "0.30.0"
tokio = { version = "1.49.0", features = ["full"] }
walkdir = "2.5.0"
